# Generated by Django 2.0.5 on 2019-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_code', models.CharField(max_length=30, verbose_name='gps编号')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='纬度')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='添加时间')),
            ],
        ),
    ]
